### ISSUE TITLE
Lyrics appear to contain a bit of garbage data?

### ISSUE THREAD

**Issue by Gazoo101** [johnwmillr/LyricsGenius#237] opened 2022-04-23 03:17 UTC
Returned Lyrics contain some garbage data, I'd assume due to a change in formatting on https://genius.com 's webpage?

All lyrics (or at least the 7 I tested) appear to lead with the following:

"\<song name> Lyrics", e.g. in the case of FreeBird, it'd be "FreeBird Lyrics"

and end with "\<number>Embed" or "Embed" at the end.

I'd say these pieces aren't supposed to be part of the lyrics, yes?

**Version info**
 - Package version [3.0.1]
 - OS: ubuntu 18.04

**Comment by Acervans** [comment] 2022-09-11 14:55
I've found the cause, in the `lyrics()` method in genius.py, the div that is searched is the one with `class_=re.compile("^lyrics$|Lyrics__Root"` however this also returns the number of "Pyongs" and the Embed button, the text content of which are included in the div. A possible solution would be to get the Lyrics_Container div instead but for some reason some lyrics are cut out.

**Comment by allerter** [comment] 2023-01-19 15:28
The PR is available at https://github.com/johnwmillr/LyricsGenius/pull/215
If you can't or don't know how to merge this PR with your own fork. Just add this 

> > I've found the cause, in the `lyrics()` method in genius.py, the div that is searched is the one with `class_=re.compile("^lyrics$|Lyrics__Root"` however this also returns the number of "Pyongs" and the Embed button from the Lyrics_Footer div, the text content of which are included in Lyrics_Root.
> > EDIT: I've seen this solved in [https://github.com/johnwmillr/LyricsGenius/pull/215#issuecomment-1083670536](url)
> 
> Hi. Your link seem to point to nowhere. Do you have the fix for this bug? I am bit too fresh with Python to start fiddling with the code myself.

The PR is available at https://github.com/johnwmillr/LyricsGenius/pull/215
Until that PR is merged and the library updated, you could fork the repository and merge this PR with your own fork.

**Comment by roaldandresen** [comment] 2023-01-19 16:23
Thank you!

**Closed** 2024-10-27 16:56 UTC
