### ISSUE TITLE
AttributeError: 'Song' object has no attribute 'year.'

### ISSUE THREAD

**Issue by zahrahosseini99** [johnwmillr/LyricsGenius#200] opened 2021-04-17 13:48 UTC
Hi,
I was trying to get a release date of a song but it shows the below error:
`>>> song_year = song.year
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Song' object has no attribute 'year.'`
I saw that [49 Years of Lyrics](https://towardsdatascience.com/49-years-of-lyrics-why-so-angry-1adf0a3fa2b4) in your examples used this method. Is this remove in later versions? or just the name of that changed?
If it was available in the previous version, could you please give me the version number?
Many thanks for considering my request.

**Comment by allerter** [comment] 2021-04-17 15:55
Hi. Yes, the `Song.year` attribute has been removed in version 3.0.0 and replaced by `Song.release_date` (which has its issue at the moment with a fix waiting to be merged at #182). The aforementioned `Song.year` is available in all versions below 3.0.0 and I suggest using 2.0.2 for the time being.

**Comment by allerter** [comment] 2021-04-17 18:21
Duplicate of #187. Closing.

**Closed by allerter** 2021-04-17 18:21 UTC
Labels: duplicate

**Comment by johnwmillr** [comment] 2021-04-17 18:29
The #182 has been merged to master.
